### ISSUE TITLE
Determine if MDP rewards are determined by (s, a) or (s, a, s')

### ISSUE THREAD

**Issue by btanner** [abhisheknaik96/differential-value-iteration#12]
[In the reference I'm using for Garnet](https://era.library.ualberta.ca/items/8fc4a1f6-95c9-4da8-aecd-96867babdf4c), rewards seem to be on outgoing (s, a)->s' edges.

```
The probability of going to each next state is generated by partitioning the unit interval at b−1 cut points
selected randomly between 0 and 1. The expected reward for each such transition is a normally
distributed random variable with mean 0 and unit variance.
```

I take this to mean that reward is defined for a (s, a, s') tuple.

In the existing micro examples, I believe it is defined for (s, a) tuples.

I can write a simple transformation to "upscale" (s, a) to (s, a, s') just by using the (s, a) reward for all resulting states. However, I'm not sure what implication that has on the algorithms or their implementations.

As a side note, the micro worlds and algorithms seem to use (a, s, s') shape, and I'm wondering if that is the most convenient, or if we might want to shift to (s, a, s').

@yiwan-rl @abhisheknaik96 Thoughts?

**Comment by btanner** [comment]
Looking at [Sridhar's paper](https://link.springer.com/content/pdf/10.1007/BF00114727.pdf), I see
```
There is also a reward or payoff function r : S x A -> R, 
where r(x, a) is the expected reward for doing action a in state x.
```

So, for this planning work, I can "downscale" the (s, a, s') rewards from GARET to (s, a) using the transition matrix to marginalize over the resulting states. I'll look into that now.

PS: I'm calling this code GARET instead of GARNET for now b/c I'm not implementing the non-stationary aspects of garNet.

**Comment by btanner** [comment]
@yiwan-rl  @abhisheknaik96 
Please take a look (PTAL), just so you know what sort of minor hiccups I've been thinking about. But, this is resolved and is visible in the new PR that brought in garet.

**Comment by yiwan-rl** [comment]
Right. The real environment produces sample rewards. For planning, the reward model we learn can produce expected rewards.
