### ISSUE TITLE
Convert MRP1 (and others?) to match the RL Book exactly.

### ISSUE THREAD

**Issue by btanner** [abhisheknaik96/differential-value-iteration#24]
Maybe something has to be changed to a "3".

**Comment by abhisheknaik96** [comment]
I think only MRP1 is from the book (Exercise 10.7), and the reward there is 1 instead of 3 that we're currently using.

**Comment by btanner** [comment]
Thx for chasing that down for me, will update later.

**Comment by btanner** [comment]
Fixed!
