### ISSUE TITLE
Review Prediction Algorithm Implementations vs Latex Descriptions

### ISSUE THREAD

**Issue by btanner** [abhisheknaik96/differential-value-iteration#25]
Ensure the code does what we mean for it to do.

**Comment by btanner** [comment]
### RVI
Question 1 for @yiwan-rl and @abhisheknaik96 
I want to be careful not to make assumptions or leaps. Can you explain the meaning/contribution of e in:
![image](https://user-images.githubusercontent.com/9030869/132067106-aeda4188-3368-4b07-ab3f-08aa1eedaca4.png)

**Comment by btanner** [comment]
DVI
- [ ] Sync
- [ ] Async

**Comment by btanner** [comment]
### MDVI
-  [ ] Sync
-  [ ] Async

**Comment by yiwan-rl** [comment]
That is right, both of them should be s'! Thanks for pointing this out!

**Comment by btanner** [comment]
This all resolved now in #33.
