### ISSUE TITLE
Questions about semantics of MDP

### ISSUE THREAD

**Issue by btanner** [abhisheknaik96/differential-value-iteration#8]
Hi @yiwan-rl , can you help me to understand how to think about some things in the code?

For example, the [MDP structure](https://github.com/abhisheknaik96/differential-value-iteration/blob/784c2b924518646203f5b53fd2f7d4b6d46d2301/src/differential_value_iteration/environments/environments.py#L52).

```
mdp1 = MDP(np.array([
    [[1.0, 0.0], [0.0, 1.0]],  # first action
    [[0.0, 1.0], [1.0, 0.0]]  # second action
]), np.array([
    [1.0, 1.0],  # first action
    [0.0, 0.0]  # second action
]), 'mdp1')
```

I want to make sure I'm clear on the semantics. Since there are 2 states and 2 actions, this array is going to be shape=(2,2,2) ;)

If we add a third action:
```
mdp1 = MDP(np.array([
    [[1.0, 0.0], [0.0, 1.0]],  # first action
    [[0.0, 1.0], [1.0, 0.0]] , # second action
    [[0.0, 1.0], [1.0, 0.0]]  # third action
]), np.array([
    [1.0, 1.0],  # first action
    [0.0, 0.0] , # second action
    [0.0, 0.0] , # third action

]), 'mdp1')
```
Now the shape of P and r are (3,2,2), and (3,2).
So, I think the first dimension is the action. This is a bit different from what I see here:
```
def num_states(self):
    return self.P.shape[0]

def num_actions(self):
    return self.P.shape[1]
```

However, action first is consistent with the algorithm implementation, and naturally with 2 states, 2 actions, everything goes through.

Just would like to get your thoughts so my code comments are correct.

**Comment by btanner** [comment]
Feel free to respond, but I think this is all sorted now.

**Comment by yiwan-rl** [comment]
Sounds good!
